const serialization = {
    "Ciao": "Kodomo",
    "CoroCoro Comic": "Kodomo",
    "Shonen Sirius": "Kodomo",
    "Pucchigumi": "Kodomo",
    "Comic BomBom": "Kodomo",
    "Weekly Shonen Jump": "Shonen",
    "Shonen Magazine": "Shonen",
    "Weekly Shonen Sunday": "Shonen",
    "Jump SQ": "Shonen",
    "Shonen Champion": "Shonen",
    "V Jump": "Shonen",
    "Monthly Shonen Magazine": "Shonen",
    "Shonen Gangan": "Shonen",
    "Shonen Ace": "Shonen",
    "Gessan": "Shonen",
    "4-Koma Nano Ace": "Seinen",
    "Bessatsu Shounen Magazine": "Shonen",
    "Comic Blade Masamune": "Shonen",
    "Comic Earth Star": "Shonen",
    "Comic Rush": "Shonen",
    "Dengeki Comic Gao!": "Shonen",
    "Dengeki Daioh": "Shonen",
    "Shounen Jets (Monthly)": "Shonen",
    "Gundam Ace": "Shonen",
    "Jump Square": "Shonen",
    "Kerokero Ace": "Shonen",
    "Keroro Land": "Shonen",
    "Magazine Special": "Shonen",
    "Monthly Comic Blade": "Shonen",
    "Monthly Comic Rex": "Shonen",
    "Monthly Dragon Age": "Shonen",
    "Monthly Shounen Ace": "Shonen",
    "Shounen Champion (Monthly)": "Shonen",
    "Shounen Magazine (Monthly)": "Shonen",
    "Monthly Shounen Rival": "Shonen",
    "Monthly Shounen Sirius": "Shonen",
    "Saikyō Jump": "Shonen",
    "Saturday AM": "Shonen",
    "Shounen Club": "Shonen",
    "Shounen Big Comic": "Shonen",
    "Shounen Jump (Weekly)": "Shonen",
    "Shounen Sunday S": "Shonen",
    "Shounen Sunday (Monthly)": "Shonen",
    "Shounen Sunday (Weekly)": "Shonen",
    "Shounen Champion (Weekly)": "Shonen",
    "Shounen Magazine (Weekly)": "Shonen",
    "Ribon Magazine": "Shojo",
    "Nakayoshi": "Shojo",
    "Bessatsu Margaret": "Shojo",
    "LaLa": "Shojo",
    "Hana to Yume": "Shojo",
    "Cheese!": "Shojo",
    "Sho-Comi": "Shojo",
    "Margaret": "Shojo",
    "Betsucomi": "Shojo",
    "Princess": "Shojo",
    "Altima Ace": "Shojo",
    "Aria": "Shojo",
    "Asuka": "Shojo",
    "Monthly Asuka Fantasy DX": "Shojo",
    "Monthly Comic Avarus": "Shojo",
    "Bessatsu Friend": "Shojo",
    "Bessatsu Hana to Yume": "Shojo",
    "Bouquet": "Shojo",
    "Chara": "Shojo",
    "ChuChu": "Shojo",
    "Cookie": "Shojo",
    "Dessert": "Shojo",
    "The Hana to Yume": "Shojo",
    "LaLa DX": "Shojo",
    "Melody": "Shojo",
    "Mimi": "Shojo",
    "Monthly Carol": "Shojo",
    "Monthly Comic Gene": "Shojo",
    "Monthly Comic Zero Sum": "Shojo",
    "Monthly Halloween": "Shojo",
    "Mystery Bonita": "Shojo",
    "Petit Flower": "Shojo",
    "Ribon Original": "Shojo",
    "Shōjo Club": "Shojo",
    "Shōjo Friend": "Shojo",
    "Sylph": "Shojo",
    "Wings": "Shojo",
    "Big Comic": "Seinen",
    "Big Comic Superior": "Seinen",
    "Morning": "Seinen",
    "Young Gangan": "Seinen",
    "Young Jump": "Seinen",
    "Young Magazine": "Seinen",
    "Big Comic Spirits": "Seinen",
    "Afternoon": "Seinen",
    "Comic Beam": "Seinen",
    "Young Animal": "Seinen",
    "Ultra Jump": "Seinen",
    "Big Comic Original": "Seinen",
    "Business Jump": "Seinen",
    "Champion RED": "Seinen",
    "Comi Digi +": "Seinen",
    "Comic Bunch": "Seinen",
    "Comic Cune": "Seinen",
    "Comic Gum": "Seinen",
    "Comic High!": "Seinen",
    "Comic Valkyrie": "Seinen",
    "Dengeki G's Comic": "Seinen",
    "Dengeki Maoh": "Seinen",
    "Evening": "Seinen",
    "Good! Afternoon": "Seinen",
    "Grand Jump": "Seinen",
    "Harta": "Seinen",
    "Kindai Mahjong": "Seinen",
    "Magi-Cu": "Seinen",
    "Manga Action": "Seinen",
    "Manga Home": "Seinen",
    "Manga Sunday": "Seinen",
    "Manga Time": "Seinen",
    "Manga Time Jumbo": "Seinen",
    "Manga Time Kirara": "Seinen",
    "Manga Time Kirara Carat": "Seinen",
    "Manga Time Kirara Forward": "Seinen",
    "Manga Time Kirara Max": "Seinen",
    "Manga Time Original": "Seinen",
    "Monthly Action": "Seinen",
    "Comic Birz": "Seinen",
    "Comic Alive": "Seinen",
    "Comic Flapper": "Seinen",
    "Monthly Comic": "Seinen",
    "Ikki": "Seinen",
    "Monthly Magazine Z": "Seinen",
    "Monthly Sunday Gene-X": "Seinen",
    "Oto Nyan": "Seinen",
    "Super Jump": "Seinen",
    "Waai!": "Seinen",
    "Weekly Manga Goraku": "Seinen",
    "Manga Times (Weekly)": "Seinen",
    "Young Jump (Weekly)": "Seinen",
    "Young Magazine (Weekly)": "Seinen",
    "Young Magazine (Monthly)": "Seinen",
    "Young Sunday (Weekly)": "Seinen",
    "Young Ace": "Seinen",
    "Young Animal Arashi": "Seinen",
    "Young Champion": "Seinen",
    "Young Comic": "Seinen",
    "Young King": "Seinen",
    "Young King (Monthly)": "Seinen",
    "Young King OURs": "Seinen",
    "Young Magazine Uppers": "Seinen",
    "Vitaman": "Seinen",
    "Be Love": "Josei",
    "Cocohana": "Josei",
    "Comic Yuri Hime": "Josei",
    "Feel Young": "Josei",
    "Flowers (Monthly)": "Josei",
    "For Mrs.": "Josei",
    "Kiss": "Josei",
    "Kiss PLUS": "Josei",
    "Comic ZERO-SUM": "Josei",
    "Petit Comic": "Josei",
    "You": "Josei",
    "Young You": "Josei",
    "Chorus": "Josei",
    "Judy": "Josei",
    "Office You": "Josei",
    "Silky": "Josei",
  };
  export default serialization;